### ISSUE TITLE
Build Error?

### ISSUE THREAD

**Issue by kevien** [JusticeRage/yara#1]
i am a newbie, CLion  Build Error? ??

**Comment by JusticeRage** [comment]
Hi! This version of Yara is modified a bit and will not work without Manalyze. It can only be built with [this project](https://github.com/JusticeRage/yara).

**Comment by kevien** [comment]
when i use CLion to compile it ,it gen an error  
yara/yara_wrapper.cpp:27:14: error: ‘nullptr’ was not declared in this scope

**Comment by JusticeRage** [comment]
`nullptr` not being recognized seems to mean that the C++11 flags are not set.
But again, those are set in Manalyze's makefile, so if you really want to build this project separately, some assembly will be required.

**Comment by kevien** [comment]
i got it ,thanks ：）
